### PR TITLE
add a linter workflow

### PR DESCRIPTION
**Pull request by elzamath**
Added a GitHub action that uses the actions/super-linter GitHub
action available on the GitHub actions Marketplace
https://github.com/github/super-linter

The action will run on modified files in a pull request. Enabled
linting for Bash, C, Go, Python Rust and Markdown.

Signed-off-by: Elza Mathew <elza.mathew@intel.com>

### CODE REVIEW

**Review by KeithWiles — APPROVED** [review]
LGTM

**Comment by jeffreybshaw** [comment]
I'd like to see the results of this. Can you convince the CI to run again? The actinos we run is based on an "allowed list" in teh settings. I added the linter action, but I don't know how to get the actinos to run when one failed because it wasn't allowed to run. 

I tried clicking the "Re-run all checks" button from the actinos screen, but that didn't work. I think you'll need to force push a change, or close and create a new PR.

**Review by jeffreybshaw — CHANGES_REQUESTED** [review]
Please run this action so we can look at the results.

**Comment by elzamath** [comment]
sure, thanks Jeff, Keith. I'll close this one and re-create it to get the job to run..

**Pull request closed without merging**
