### PR TITLE
add a linter workflow

### PR DESCRIPTION
**Pull request by elzamath**
Added a GitHub action that uses the actions/super-linter GitHub
action available on the GitHub actions Marketplace
https://github.com/github/super-linter

The action will run on modified files in a pull request. Enabled
linting for Bash, C, Go, Python Rust and Markdown.

Signed-off-by: Elza Mathew <elza.mathew@intel.com>

### CODE REVIEW

**Comment by jeffreybshaw** [comment]
It says the check passed, but I'm not convinced it did anything. I would have expected it to list some files in the "Files to Check:" section, right?

**Comment by elzamath** [comment]
Right! It didn't do anything. That's because VALIDATE_ALL_CODEBASE: false so only edited files on this PR are checked. Since the only edited file in this PR is a yml file , the enabled linters don't run on this PR. Enabled linters are clang-format, bash, Go, Rust, Python and Markdown which don't match .yml file. Since I explicitly set the VALIDATE_<LANGUAGE> env variables to true for these languages, that means I opted to disable the rest of the linters according to the behavior mentioned here https://github.com/github/super-linter#environment-variables  I saw a linter you could enable for GitHub actions VALIDATE_GITHUB_ACTIONS: true, let me enable that and see if it runs on this PR. There also seems to be a VALIDATE_YAML env variable you can set to lint yaml files but that's probably not what we want.

**Comment by jeffreybshaw** [comment]
> Right! It didn't do anything. That's because VALIDATE_ALL_CODEBASE: false so only edited files on this PR are checked. 

Ah, that makes sense. I think this is a good idea. Let's merge it and see how it goes!

**Review by jeffreybshaw — APPROVED** [review]

**Comment by KeithWiles** [comment]
At some point we may want to make this a requirement to merging.

**Pull request merged**
