### PR TITLE
Fix includes inside extern

### PR DESCRIPTION
**Pull request by elzamath**

### CODE REVIEW

**Review by KeithWiles — APPROVED** [review]
LGTM

**Comment by KeithWiles** [comment]
@manojgop can you please verify that Rust is building correctly with this change.

**Comment by jeffreybshaw** [comment]
> @manojgop can you please verify that Rust is building correctly with this change.

I attempted to build the Rust bindings but ran into some errors unrelated to these changes. The rust bindings don't build out of the box, at least for me. I get lots of errors regarding versions and editions. I'm going to go ahead and merge this change while Manoj continues working on the Rust bindings.

**Comment by manojgop** [comment]
> > @manojgop can you please verify that Rust is building correctly with this change.
> 
> I attempted to build the Rust bindings but ran into some errors unrelated to these changes. The rust bindings don't build out of the box, at least for me. I get lots of errors regarding versions and editions. I'm going to go ahead and merge this change while Manoj continues working on the Rust bindings.

@jeffreybshaw - Is clang installed. `sudo apt-get install clang`. What's output of `cargo --version` ? It could be due to clang not installed.

**Pull request merged**
